/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.*;
import java.sql.*;
import javax.imageio.ImageIO;
/**
 *
 * @author Mr. J
 */
public class Final extends login {

    /**
     * Creates new form Final
     */
    public Final() {
        initComponents();
        try{
        BufferedImage img = ImageIO.read(getClass().getResource("\\Images\\ico.jpg"));
        setIconImage(img);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        setResizable(false);
        setLocationRelativeTo(null);
        String id = getid();
        invis();
        n=start.cat();
        String om1="0",om2="0",om3="0",om4="0",om5="0",otm="0";
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/gg","root","");
        Statement st = con.createStatement();
        String s0 = "select * from dt where id='"+id+"'";        
        ResultSet rs = st.executeQuery(s0);
        while(rs.next())
        {
            om1 = rs.getString("m1");
            om2 = rs.getString("m2");
            om3 = rs.getString("m3");
            om4 = rs.getString("m4");
            om5 = rs.getString("m5");
            otm = rs.getString("tm");
        }
        if(n==1)
        {
            m1 = A5.mark();
            tm = Integer.parseInt(otm);
            tm = tm - Integer.parseInt(om1);
            tm = tm +m1;
            if(tm>2500)
            {
                tm=2500;
            }
            if(m1>500)
            {
                m1=500;
            }
            om1 = String.valueOf(m1);
            otm = String.valueOf(tm);
            ss = "update dt set m1='"+om1+"',tm='"+otm+"' where id = '"+id+"'";        
            jLabel2.setText("Your Score is "+m1+".");
        }
        if(n==2)
        {
            m2 = B5.mark();
            tm = Integer.parseInt(otm);
            tm = tm - Integer.parseInt(om2);
            tm = tm +m2;
            if(tm>2500)
            {
                tm=2500;
            }
            if(m2>500)
            {
                m2=500;
            }
            om2 = String.valueOf(m2);
            otm = String.valueOf(tm);
            ss = "update dt set m2='"+om2+"',tm='"+otm+"' where id = '"+id+"'";
            jLabel2.setText("Your Score is "+m2+".");
        }
        if(n==3)
        {
            m3 = C5.mark();
            tm = Integer.parseInt(otm);
            tm = tm - Integer.parseInt(om3);
            tm = tm +m3;
            if(tm>2500)
            {
                tm=2500;
            }
            if(m3>500)
            {
                m3=500;
            }
            om3 = String.valueOf(m3);
            otm = String.valueOf(tm);
            ss = "update dt set m3='"+om3+"',tm='"+otm+"' where id = '"+id+"'";
            jLabel2.setText("Your Score is "+m3+".");
        }
        if(n==4)
        {
            m4 = D5.mark();
            tm = Integer.parseInt(otm);
            tm = tm - Integer.parseInt(om4);
            tm = tm +m4;
            if(tm>2500)
            {
                tm=2500;
            }
            if(m4>500)
            {
                m4=500;
            }
            om4 = String.valueOf(m4);
            otm = String.valueOf(tm);
            ss = "update dt set m4='"+om4+"',tm='"+otm+"' where id = '"+id+"'";
            jLabel2.setText("Your Score is "+m4+".");
        }
        if(n==5)
        {
            m5 = E5.mark();
            tm = Integer.parseInt(otm);
            tm = tm - Integer.parseInt(om5);
            tm = tm +m5;
            if(tm>2500)
            {
                tm=2500;
            }
            if(m5>500)
            {
                m5=500;
            }
            om5 = String.valueOf(m5);
            otm = String.valueOf(tm);
            ss = "update dt set m5='"+om5+"',tm='"+otm+"' where id = '"+id+"'";
            jLabel2.setText("Your Score is "+m5+".");
        }
        st.executeUpdate(ss);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
int n;
static int m1,m2,m3,m4,m5,tm;
String ss;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Huh!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Game Over !!!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("oK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(204, 204, 204))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ui ui1 = new ui();
        setVisible(false);
        ui1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
